filenames:
  Cargo.toml: "📦"
  package.json: "📦"
  Dockerfile: "🐳"
  README.md: "📖"
  .gitignore: "🙈"
  config.fish: "🐟"
  init.lua: "🌙"
  nginx.conf: "🌐"

extensions:
  rs: "🦀"
  js: "🟨"
  ts: "🔷"
  py: "🐍"
  go: "🐹"
  md: "📝"
  yaml: "📄"
  yml: "📄"
  json: "📋"
  fish: "🐟"
  lua: "🌙"
  conf: "⚙️"
  log: "📋"

size:
  - size: 0
    color: "0,150,0"
  - size: 1024
    color: "150,150,0"
  - size: 1048576
    color: "150,100,0"
  - size: 1073741824
    color: "150,0,0"
